### ISSUE TITLE
Can't get an access token

### ISSUE THREAD

**Issue by eveningkid** [OmarElGabry/lumen-api-oauth#1]
Hi Omar,

First of all, thanks for doing this. I'm pretty new to Lumen, so your tutorial definitely helped me to found out how all this is working!

Now, the bad news: I can't find a way to get an access token using Postman. 
Here are the [`users`](http://image.prntscr.com/image/ac5e2b95886849c58e892ec58a5866f1.png) and [`oauth_clients`](http://image.prntscr.com/image/54a393477dc44a10a725c63d89fa9978.png) tables I have now.
Also, here's [the POST request I send, and its response](http://image.prntscr.com/image/f90b88dfb3b24572ba393695a9555e11.png).

What am I missing? If you need any other information, feel free to ask me and I'll provide the according details. 😊 

Thank you for your time!

**Comment by blacknet76** [comment]
Hey, 
your problem is, you have set the parameters and values in the Headers and not in the Body section.
Best regards

**Comment by eveningkid** [comment]
Wow, one of these moments I feel so mad at myself! 
Thank you, it works perfect now @blacknet76!

Have a nice day my friend.
