### ISSUE TITLE
Problem using oauth2

### ISSUE THREAD

**Issue by sethhorsley** [OmarElGabry/lumen-api-oauth#2]
Wouldn't it be better to use passport instead of using oauth2 which isn't supported anymore?

**Comment by OmarElgabry** [comment]
Is passport supported for Lumen? No. Even if there are other work around but we can still [wait for it](https://twitter.com/jordyalblas/status/773634210527674368)

**Comment by sethhorsley** [comment]
this should work [lumen-passport](https://github.com/dusterio/lumen-passport)

**Comment by OmarElgabry** [comment]
Yes, I am aware of it. I am saying even if there are work around, like the one you sent, you will have better options in the future, assuming passport will support Lumen as mentioned by Taylor.

**Comment by sethhorsley** [comment]
gotcha, If I have some time I'll see if I can add native support for it
