### ISSUE TITLE
Error when I send the post 

### ISSUE THREAD

**Issue by efrainepayco** [OmarElGabry/lumen-api-oauth#3]
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"grant_type\" parameter."}

How do I can solve this error?

Thanks in advance

**Comment by OmarElgabry** [comment]
Please show me the parameters you've sent in the HTTP POST request. 

In the meanwhile, you basically need to get a list of users using `/users` path. Then, copy and paste any user details aside. Now, make a POST request to `/oauth/access_token` to get an access token passing:

The **username**: The email of the user.
The **password**: The value is _secret_.
The **client_id** & **client_secret**: They are id0 & secret0, or id1 & secret1, ...etc respectively.
The **grant_type**: The value is _password_.

**Comment by efrainepayco** [comment]
Thanks bro!

The problem was solved, I was bad estructured the way that I send parameters, correct way is body with form-data
