### ISSUE TITLE
migrate --seed error

### ISSUE THREAD

**Issue by henriqueweiand** [OmarElGabry/lumen-api-oauth#4]
![captura de tela de 2017-08-24 10-01-50](https://user-images.githubusercontent.com/6539492/29667576-4a1f1aca-88b3-11e7-96e9-c0fde4c753f0.png)

Using postgre

**Comment by sethhorsley** [comment]
You docker cointainer isnt configured to use lumen.

**Comment by sethhorsley** [comment]
try using http://laradock.io if you plan on using docker and lumen
