### ISSUE TITLE
use laravel/passport

### ISSUE THREAD

**Issue by slawa-dev** [OmarElGabry/lumen-api-oauth#6]
When installing with composer you will get a warning:

Package lucadegasperi/oauth2-server-laravel is abandoned, you should avoid using it. Use laravel/passport instead.

https://github.com/lucadegasperi/oauth2-server-laravel

> Note: This package is no longer maintaned for Laravel 5.3+ since Laravel now features the Passport package.

e.g.
https://github.com/dusterio/lumen-passport

**Comment by OmarElgabry** [comment]
It's almost the same issue as #2.

The idea is passport is _not_ supported for Lumen. Even if there are work around, like the one you sent, you will have better options in the future, assuming passport will support Lumen as [mentioned by Taylor](https://twitter.com/jordyalblas/status/773634210527674368).

**Comment by sethhorsley** [comment]
How do you know this feature will be implemented because I have asked Taylor about it and no answer.
I think the best solution is lumen-passport. If you want I will start working on implementing it soon especially bc I and using this in production.

**Comment by slawa-dev** [comment]
@iseth Taylor recently said he had already some of the Passport features working for Lumen. But there is no ETA. It can take a while...

I decided to create my project that needs REST API in Laravel with Passport.
It is slower, but later we will also use a web front end and I will just use Laravel to implement it.

Right now is just a bad time because Passport is out but not ready for Lumen. Many developers stopped working on projects ([lucadegasperi/oauth2-server-laravel](https://github.com/lucadegasperi/oauth2-server-laravel)) that will be replaced by passport soon.

**Comment by OmarElgabry** [comment]
@iseth Your question is like "How do you know you'll live tomorrow?". For sure no one knows the future. But, In his reply, he explicitly mentioned that he has future plans for Lumen with Passport. That's all.

In the meanwhile, you can use [lumen-passport](https://github.com/dusterio/lumen-passport) or use Laravel with Passport.
